### ISSUE TITLE
Docs and demo page is 404

### ISSUE THREAD

**Issue by jeanbaptistesouvestre** [storybookjs/addon-designs#187]
### Affected design types

- [ ] figma
- [ ] figspec
- [ ] link
- [ ] image
- [ ] iframe

### Describe the bug

The link displayed in the readme, and the sidebar https://pocka.github.io/storybook-addon-designs is 404

### How to reproduce the bug?

Go to https://pocka.github.io/storybook-addon-designs

### Expected behaviour

https://pocka.github.io/storybook-addon-designs correctly displays doc and demo, 

or links are updated to the correct url

### Environment

- [ ] Chrome / Chromium / Chromium based browsers
- [ ] Firefox
- [ ] macOS Safari
- [ ] iOS Safari
- [ ] Samsung Internet
- [X] Other

### Affected versions

N/A

### Storybook versions

N/A

**Comment by ryarturogi** [comment]
Yep, 404 down

**Comment by yannbf** [comment]
Hey peeps! The project has recently been moved between repos, which is why the website is down.
@pocka what do you think is the best way forward? should we host this on netlify or something?

**Comment by pocka** [comment]
@yannbf 
I disabled the GitHub Pages as I thought it affects billing (traffic and/or file size, turns out wrong)... I have no strong opinion about where to host. Hosting on Storybook org maintainers' preferable service would be the best for maintainability. If code tweaks or something is needed, please let me know.
(Re-enabling GitHub Pages would be easy: just restore [`deploy-ghpages.yml`](https://github.com/storybookjs/addon-designs/commit/c034db2d91a9f3f956b274441b9104bf5af5b99d#diff-64586c81bb018e126cfdff2eae5b8672383f3d84bf9ccc06c09017f4f909c986))

**Comment by valioDOTch** [comment]
It seems that this project is now linking to https://storybookjs.github.io/addon-designs for "Docs & Demos"

However that's also a dead-end.

**Comment by pocka** [comment]
@yannbf 
Let me know if you are okay with hosting "Docs & Demos" under `https://storybookjs.github.io/addon-designs`, I'll re-enable GH Pages hosting workflow and make sure everything works then.

**Comment by yannbf** [comment]
Thanks pocka! This issue has been solved, the demo pages are available now, though they should be updated as they are still showing Storybook 6.5

cc @thafryer

**Comment by thafryer** [comment]
@pocka Can you go ahead and re-enable the GH pages hosting workflow?
