### ISSUE TITLE
Figma url not loading

### ISSUE THREAD

**Issue by refugedesigns** [storybookjs/addon-designs#242]
### Affected design types

- [X] figma
- [ ] figspec
- [ ] link
- [ ] image
- [ ] iframe

### Describe the bug

I installed storybook version 8.0.8 and added the storybook-addon-design but, the panel shows an error "refuse to connect" with I add a figma link.

![image](https://github.com/storybookjs/addon-designs/assets/70457144/1768c7f1-04c7-4137-a4f1-7ae8c8624bae)
![image](https://github.com/storybookjs/addon-designs/assets/70457144/ded6eb89-c376-4b38-aa7e-6d83a4d6e5f9)

### How to reproduce the bug?

1. install storybook-addon-design version 8.0.2
2. add plugin to addons in main.js/main.ts
3. restart storybook 
4. add a design object in any storybook config file in the parameters object with type:"figma" and url:"figma image url"
5. design tab shows "refused to connect"

### Expected behaviour

Should load the picture from the figma link

### Environment

- [X] Chrome / Chromium / Chromium based browsers
- [ ] Firefox
- [ ] macOS Safari
- [ ] iOS Safari
- [ ] Samsung Internet
- [ ] Other

### Affected versions

8.0.2

### Storybook versions

8.0.8

**Comment by amorfee** [comment]
Encountering the same issues. Appears to be due to Figma's Content Security Policy for frame-ancestors:

> Refused to frame 'https://www.figma.com/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self' vscode-webview: vscode-file:".

**Comment by pocka** [comment]
Cannot reproduce, [live demo](https://storybookjs.github.io/addon-designs/?path=/story/docs-figma-examples--embed-file) is working. Please fill complete reproduce steps.

But seeing your screenshot contains a new Figma share URL format, I suspect this is same as #239.
Their embed page does not include CSP so I guess the addon fallbacks to regular iframe embeds.
If this is due to the new URL format, workaround is (from https://github.com/storybookjs/addon-designs/issues/239#issue-2301111721):

> ...So my workaround so far has been to use the Copy link to selection and simply swap out `design` with `file`.

**Comment by amorfee** [comment]
Confirming changing `design` to `file` worked in my instance.

**Comment by amir-e-uidb** [comment]
same here, `design` to `file` working like a charm! good luck
